"""empty message

Revision ID: fd78bf2f1fe7
Revises: 6c253247ad0d
Create Date: 2025-09-10 11:10:15.135709

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd78bf2f1fe7"
down_revision: Union[str, Sequence[str], None] = "6c253247ad0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "branches",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "specialities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("correct_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "filial_speciality",
        sa.Column("filial_id", sa.BigInteger(), nullable=False),
        sa.Column("speciality_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["filial_id"], ["branches.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["speciality_id"], ["specialities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("filial_id", "speciality_id"),
    )
    op.create_table(
        "doctor_documents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("doctor_id", sa.BigInteger(), nullable=False),
        sa.Column("file_url", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["doctor_id"], ["doctors.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_doctor_documents_doctor_id"),
        "doctor_documents",
        ["doctor_id"],
        unique=False,
    )
    op.create_table(
        "doctor_speciality",
        sa.Column("doctor_id", sa.BigInteger(), nullable=False),
        sa.Column("speciality_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"], ["doctors.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["speciality_id"], ["specialities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("doctor_id", "speciality_id"),
    )
    op.add_column(
        "doctors", sa.Column("full_name", sa.String(), nullable=False)
    )
    op.add_column(
        "doctors", sa.Column("filial_id", sa.BigInteger(), nullable=False)
    )
    op.add_column(
        "doctors",
        sa.Column(
            "is_active", sa.Boolean(), server_default="True", nullable=False
        ),
    )
    op.add_column(
        "doctors", sa.Column("photo_url", sa.String(), nullable=True)
    )
    op.add_column(
        "doctors", sa.Column("education", sa.String(), nullable=True)
    )
    op.add_column("doctors", sa.Column("about", sa.Text(), nullable=True))
    op.alter_column(
        "doctors",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=False,
    )
    op.create_foreign_key(
        None, "doctors", "branches", ["filial_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "doctors", type_="foreignkey")
    op.alter_column(
        "doctors",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=False,
    )
    op.drop_column("doctors", "about")
    op.drop_column("doctors", "education")
    op.drop_column("doctors", "photo_url")
    op.drop_column("doctors", "is_active")
    op.drop_column("doctors", "filial_id")
    op.drop_column("doctors", "full_name")
    op.drop_table("doctor_speciality")
    op.drop_index(
        op.f("ix_doctor_documents_doctor_id"), table_name="doctor_documents"
    )
    op.drop_table("doctor_documents")
    op.drop_table("filial_speciality")
    op.drop_table("specialities")
    op.drop_table("branches")
    # ### end Alembic commands ###
